In [1]:
import numpy as np

# Fast number crunching with NumPy
a = np.arange(1, 11)
b = np.linspace(10, 100, 10)

# vectorized operations
sum_ab = a + b
prod_ab = a * b
mean_ab = np.mean(sum_ab)
std_ab = np.std(prod_ab)

a, b, sum_ab, prod_ab, mean_ab, std_ab

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]),
 array([ 11.,  22.,  33.,  44.,  55.,  66.,  77.,  88.,  99., 110.]),
 array([  10.,   40.,   90.,  160.,  250.,  360.,  490.,  640.,  810.,
        1000.]),
 np.float64(60.5),
 np.float64(324.1990129534635))